development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: editoraldb
  username: root
  password: Wasser

text:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: editoraldb
  username: root
  password: Wasser

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: editoraldb
  username: root
  password: Wasser