development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: editoraldb
  pool: 5
  username: root
  password: Wasser
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: editoraldb
  pool: 5
  username: root
  password: Wasser
  socket: /tmp/mysql.sock